# Generated by Django 4.1.7 on 2023-08-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.CharField(blank=True, max_length=120, verbose_name='Owner'),
        ),
    ]
